version: '3.8'

services:
  postgres-dev:
    image: postgres:16
    container_name: abbalm-dev-db
    environment:
      POSTGRES_DB: abbalm-dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-dev-data: